apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-essd
  labels:
    alicloud-pvname: pv-essd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-essd
    volumeAttributes:
      server: "25***49129-ys**7.cn-shenzhen.nas.aliyuncs.com"
      path: "/csi"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3
